version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports: 
      - 4566:4566
      - '8080:8080' # Port for LocalStack web dashboard
    environment:
      - EDGE_PORT=4566
      - BROWSING-TOPICS=1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy 
    volumes:
      # - './.localstack:/tmp/localstack'
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - '/var/run/docker.sock:/var/run/docker.sock'