name: Sandbox
run-name: Deploy to Sandbox by ${{ github.actor }} on branch ${{ github.ref }}

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
 deploy:
    uses: prandogabriel/sls-appointments/.github/workflows/reusable_workflows_deploy.yml@main
    with:
      stage: sandbox
      region: us-west-1
    secrets: inherit



